
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ivned
 */
public class FrmAgregarPeliculaoSerie extends javax.swing.JFrame {

   /**
    * Creates new form FrmAgregarPelicula
    */
   public FrmAgregarPeliculaoSerie() {
      initComponents();
      chcClasificacion.add("A");
      chcClasificacion.add("B");
      chcClasificacion.add("B15");
      chcClasificacion.add("G");
      chcClasificacion.add("R13");
      chcClasificacion.add("R16");
      
      chcGenero.add("Ciencia Ficcion");
      chcGenero.add("Accion");
      chcGenero.add("Suspenso");
      chcGenero.add("Comedia");
      chcGenero.add("Terror");
      chcGenero.add("Drama");
      chcGenero.add("Comedias");
      chcGenero.add("Musical");
      
      chcContenido.add("Series");
      chcContenido.add("Peliculas");
      
      
      
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      lblTitulo = new javax.swing.JLabel();
      lblGenero = new javax.swing.JLabel();
      lblContenido = new javax.swing.JLabel();
      txtTitulo = new javax.swing.JTextField();
      chcClasificacion = new java.awt.Choice();
      btnAgregarPelicula = new java.awt.Button();
      chkEstreno = new java.awt.Checkbox();
      chcGenero = new java.awt.Choice();
      lblClasificacion1 = new javax.swing.JLabel();
      chcContenido = new java.awt.Choice();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

      lblTitulo.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
      lblTitulo.setText("Titulo:");

      lblGenero.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
      lblGenero.setText("Genero:");

      lblContenido.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
      lblContenido.setText("Serie o Pelicula:");

      txtTitulo.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
      txtTitulo.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            txtTituloActionPerformed(evt);
         }
      });

      chcClasificacion.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N

      btnAgregarPelicula.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
      btnAgregarPelicula.setLabel("Agregar");
      btnAgregarPelicula.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnAgregarPeliculaActionPerformed(evt);
         }
      });

      chkEstreno.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
      chkEstreno.setForeground(new java.awt.Color(255, 255, 255));
      chkEstreno.setLabel("Estreno");

      chcGenero.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N

      lblClasificacion1.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
      lblClasificacion1.setText("Clasificacion:");

      chcContenido.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                  .addGap(10, 10, 10)
                  .addComponent(chkEstreno, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGroup(layout.createSequentialGroup()
                  .addGap(135, 135, 135)
                  .addComponent(btnAgregarPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGroup(layout.createSequentialGroup()
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblContenido, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                     .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                     .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                           .addComponent(chcClasificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(chcContenido, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))))
               .addGroup(layout.createSequentialGroup()
                  .addContainerGap()
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(lblGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(lblClasificacion1))
                  .addGap(38, 38, 38)
                  .addComponent(chcGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGap(40, 40, 40))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGap(37, 37, 37)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(lblTitulo)
               .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(34, 34, 34)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(lblContenido)
               .addComponent(chcContenido, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(16, 16, 16)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(lblClasificacion1)
               .addComponent(chcClasificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                  .addGap(20, 20, 20)
                  .addComponent(chcGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGroup(layout.createSequentialGroup()
                  .addGap(18, 18, 18)
                  .addComponent(lblGenero)))
            .addGap(18, 18, 18)
            .addComponent(chkEstreno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(10, 10, 10)
            .addComponent(btnAgregarPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(34, Short.MAX_VALUE))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void txtTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTituloActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_txtTituloActionPerformed

   private void btnAgregarPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPeliculaActionPerformed
      String titulo=txtTitulo.getText();
      String clasificacion=chcClasificacion.getSelectedItem();
      String genero=chcGenero.getSelectedItem();
      boolean estreno =chkEstreno.getState();
      if(FrmPrincipal.inventario.agregarPelicula(titulo, clasificacion, genero, estreno))
      JOptionPane.showMessageDialog(this,"Pelicula/Serie Agregada Exitosamente");
      else
      JOptionPane.showMessageDialog(this, "Espacio Insuficiente");
      this.dispose();
   }//GEN-LAST:event_btnAgregarPeliculaActionPerformed

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(FrmAgregarPeliculaoSerie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(FrmAgregarPeliculaoSerie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(FrmAgregarPeliculaoSerie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(FrmAgregarPeliculaoSerie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            new FrmAgregarPeliculaoSerie().setVisible(true);
         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private java.awt.Button btnAgregarPelicula;
   private java.awt.Choice chcClasificacion;
   private java.awt.Choice chcContenido;
   private java.awt.Choice chcGenero;
   private java.awt.Checkbox chkEstreno;
   private javax.swing.JLabel lblClasificacion1;
   private javax.swing.JLabel lblContenido;
   private javax.swing.JLabel lblGenero;
   private javax.swing.JLabel lblTitulo;
   private javax.swing.JTextField txtTitulo;
   // End of variables declaration//GEN-END:variables
}
