/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ivned
 */
public class FrmMostrarInventario extends javax.swing.JFrame {
private byte x=1;
   /**
    * Creates new form FrmMostrarInventario
    */
   public FrmMostrarInventario() {
      initComponents();
       btnAnterior.setEnabled(false);
        if(FrmPrincipal.inventario.getTotal()<=1)
            btnSiguiente.setEnabled(false);
        else
            btnSiguiente.setEnabled(true);
       
        String pelicula=FrmPrincipal.inventario.getPelicula((byte)x);
        txaPelicula.setText(pelicula);
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      btnAnterior = new javax.swing.JButton();
      btnSiguiente = new javax.swing.JButton();
      jScrollPane1 = new javax.swing.JScrollPane();
      txaPelicula = new javax.swing.JTextArea();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
      getContentPane().setLayout(null);

      btnAnterior.setBackground(new java.awt.Color(0, 0, 0));
      btnAnterior.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 18)); // NOI18N
      btnAnterior.setText("Anterior");
      btnAnterior.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnAnteriorActionPerformed(evt);
         }
      });
      getContentPane().add(btnAnterior);
      btnAnterior.setBounds(20, 195, 150, 50);

      btnSiguiente.setBackground(new java.awt.Color(0, 0, 0));
      btnSiguiente.setFont(new java.awt.Font("Gill Sans Ultra Bold", 3, 18)); // NOI18N
      btnSiguiente.setText("Siguiente");
      btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnSiguienteActionPerformed(evt);
         }
      });
      getContentPane().add(btnSiguiente);
      btnSiguiente.setBounds(230, 190, 160, 50);

      jScrollPane1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
      jScrollPane1.setForeground(new java.awt.Color(0, 0, 0));
      jScrollPane1.setFont(new java.awt.Font("Kristen ITC", 2, 18)); // NOI18N

      txaPelicula.setColumns(20);
      txaPelicula.setRows(5);
      jScrollPane1.setViewportView(txaPelicula);

      getContentPane().add(jScrollPane1);
      jScrollPane1.setBounds(20, 18, 370, 150);

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed

      String pelicula=FrmPrincipal.inventario.getPelicula((byte)--x);
      txaPelicula.setText(pelicula);
      if(x==1)
      btnAnterior.setEnabled(false);
      if(!btnSiguiente.isEnabled())
      btnSiguiente.setEnabled(true);

   }//GEN-LAST:event_btnAnteriorActionPerformed

   private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
      String pelicula=FrmPrincipal.inventario.getPelicula((byte)++x);
      txaPelicula.setText(pelicula);
      if(x==FrmPrincipal.inventario.getTotal())
      btnSiguiente.setEnabled(false);
      if(!btnAnterior.isEnabled())
      btnAnterior.setEnabled(true);

   }//GEN-LAST:event_btnSiguienteActionPerformed

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(FrmMostrarInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(FrmMostrarInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(FrmMostrarInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(FrmMostrarInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            new FrmMostrarInventario().setVisible(true);
         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton btnAnterior;
   private javax.swing.JButton btnSiguiente;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JTextArea txaPelicula;
   // End of variables declaration//GEN-END:variables
}
