
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ivned
 */
public class FrmPrincipal extends javax.swing.JFrame {
public byte tamañoInventario=6;
public static Inventario inventario; 
   /**
    * Creates new form FrmPrincipal
    */
   public FrmPrincipal() {
      inventario=new  Inventario (tamañoInventario);
      initComponents();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      mostrar_peliculas_del_inventario = new javax.swing.JButton();
      Agregar_pelicula_al_inventario = new javax.swing.JButton();
      label1 = new java.awt.Label();
      label2 = new java.awt.Label();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
      setBackground(new java.awt.Color(204, 0, 0));

      mostrar_peliculas_del_inventario.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
      mostrar_peliculas_del_inventario.setText("Mostrar el Inventario");
      mostrar_peliculas_del_inventario.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            mostrar_peliculas_del_inventarioActionPerformed(evt);
         }
      });

      Agregar_pelicula_al_inventario.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
      Agregar_pelicula_al_inventario.setText("Agregar Nueva Pelicula/Serie");
      Agregar_pelicula_al_inventario.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            Agregar_pelicula_al_inventarioActionPerformed(evt);
         }
      });

      label1.setAlignment(java.awt.Label.CENTER);
      label1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
      label1.setForeground(new java.awt.Color(0, 0, 0));
      label1.setText("Bienvenido Usuari@");

      label2.setAlignment(java.awt.Label.CENTER);
      label2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
      label2.setForeground(new java.awt.Color(0, 0, 0));
      label2.setText("Que deseas Realizar");

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap(27, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addComponent(Agregar_pelicula_al_inventario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(mostrar_peliculas_del_inventario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addGroup(layout.createSequentialGroup()
                  .addGap(19, 19, 19)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGap(38, 38, 38))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGap(62, 62, 62)
            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(Agregar_pelicula_al_inventario, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(mostrar_peliculas_del_inventario, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(35, Short.MAX_VALUE))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void mostrar_peliculas_del_inventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrar_peliculas_del_inventarioActionPerformed

      if(inventario.getTotal()>0){
         javax.swing.JFrame frmMostrar=new FrmMostrarInventario();
         frmMostrar.setSize(400, 500);
         frmMostrar.setVisible(true);
      }else
      JOptionPane.showMessageDialog(this, "Inventario Vacio");
   }//GEN-LAST:event_mostrar_peliculas_del_inventarioActionPerformed

   private void Agregar_pelicula_al_inventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Agregar_pelicula_al_inventarioActionPerformed

      if(inventario.getTotal()<tamañoInventario){
         javax.swing.JFrame frmAgregar= new FrmAgregarPeliculaoSerie();
         frmAgregar.setSize(400,400);
         frmAgregar.setVisible(true);
      }else
      JOptionPane.showMessageDialog(this,"Inventario lleno");
   }//GEN-LAST:event_Agregar_pelicula_al_inventarioActionPerformed

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            new FrmPrincipal().setVisible(true);
         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton Agregar_pelicula_al_inventario;
   private java.awt.Label label1;
   private java.awt.Label label2;
   private javax.swing.JButton mostrar_peliculas_del_inventario;
   // End of variables declaration//GEN-END:variables

   
}
